sudo: required

language: java

jdk:
- openjdk10

services:
- docker

script:
- make bump-version
- make

after_success:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- git config user.name team-helse[bot]
- git config user.email team-helse[bot]@users.noreply.github.com
- "./travis/deploy.sh"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
- openssl aes-256-cbc -K $encrypted_7f8420691ff5_key -iv $encrypted_7f8420691ff5_iv
  -in travis/my-private.key.enc -out travis/private.pem -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export INSTALLATION_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/private.pem $GITHUB_APP_ID`)

env:
  global:
  - secure: YituTIcu8HcW4yy53imHBUi4jNQj+xKGA/Z7BQjV0f84sMGgNm164aKawJKZV3lcA91ZQ6ORWbMuatkldBDCWdY07Hm8Ijioj6Es2KDsLFGLLWFWTpuPla7SPWaxebsPDLGiIv23QuEncpUf2Z1vietAMqo+f/9pEcpZu2bBzMn5rl7/LkVJ577fnsEgBmYjNED5V+PRGo7UIG3/3wE0DGk+LeFt7EHD4cc2aRXKXUbnjIS/d2av4EfJvlasbRseQ0H5WvYyjayyI6IK9rEKd9qQpjCvtN1g3GKJ/iKOLs1seUmUcdTm06upJo2DW7CNqNdTnZLdOCOUm8VAiC4oWS+wauHt+GgHbIo+VUc2nW9j4rnBJORM3IjGOVsApn57cO8sR1xZPMSmO73TuN/msvT2kXxfeaDIljZhnrllpHAZncBTWZ9e53/g+S/pkM4rRwdTg8DojCmJZMTId96LBq72MNYFdpGXTdpph1NlGugwLqzRjdrDXVrwTazVK5NDI9Bb9t/0QWdFXTKoNYdYeYK+1gqaykbVwwBghSATttHFe+BgXQLktVmD/pJuielcj1FgPA/+wDSUuLKch+8yYJUplCHpwh6rG+mr2bX4yFt3f+2NlUFvg9k9GD84DP+uOOdCEuVAfucKuHuw87gioMQlSmtdvVUoGW9INu3OIHo=
  - secure: SBrY0OwacFrVazvIqjDvqCohavx5cXT/ioKIdIm/tX40XCZJiJkBmuRI1ONNYVKrz+cUD/NYS+r5ehkLooyONnGFgWZu5Wmhj/4DepYwbDcA8/3eFfNTWbXhGpzXbFy82Eiy/WOsmvxyJSjJWXnarxrI3Vs3cGBGPLM68kUWgszcqJ+AodDIYwisw2Tbd6Q7WW7Gk6SDvxwh3zChMvs335KZYTxjnbhJ/KDXky0nplOYzpdrK2Gf28s4ETDBjGbHnLm1FGv5xdKWFgpKMGWDnv9vYHr28KOOgLA5NvVCb42VbbLb1p7Ac/D7v3LNulRdH/la7ZARirS6+wbaJAy0/Ja4wt8eGinBDJG83ZQ//cv1/UE4wx0ohFYAjJrmEELLtNdwmCRFa7N7uCU+XVTE665LkjADoP2HEA6yihX8niDh/MMyOl5OBsMkBeaPD6PF8oI00j6mtfHAf3axAR6jcsUPimNJ4NfT5rvjLBe1SMtdr8B89qPHb1a/ATrTo+q5E+rxxYVf62yk9G2zEmtsfXIUCjzUcYYJRs7khk8EN0Nx7SJTvrsTotAQchZC6NWCdUMvKrHlUdfaizxycSjJEAV+DRZOioramJGcYHUA07Pn1FQ6iWfHnLj0LGnH8mC6NRa+QFTXeMydT3pBoNmqC3fZ56OgJQYNJH6JPuxYpas=
  - secure: usIjyFhHnN3LzLbSvmlaFSMbRb++76hE5xVnUlVX0x0eUA3QEqlipAYX/hMHUy+O6zFaK/Ny30LvkP63KGddZKo378mXXYN+befvf2dULnGyvSYmzG+8zP3i9eB8wG5MVMFHPrEHsTp9qSxVL2VVoZ2+9/zH6+DbGi/Q7F4jC1JMteVYjdAhAZZwn1sBpr6SIF+EL2f+QvoJCc9cOL5XfmoLCbZxEzw5Zcx3hE7badj7R5pDNjtERliqSEH47tfxLq9emFLSqcHpxt6UAj8EhnP2jvNRITVhLlMmZCpdTZkqlHAXBD7TASQJrFguPtpeN4Jm0lAd9bPrqDKF8IGM/75rksZdq9tAYtEMMHpqEw1ORAZqjueJCMD009pcxhqeucFTxulAzTPs8h+o8AhiDZMyDyohRxjkmkY/Ngt8o//omyaZEQpNS0AFXf4bu2iGX7uqDYNfCAKbYhuhuKNs6Lp9bUAFJUNO6ZkyPRkPpuyAuIqvaDaX+OdUGjqwJVtJz8ctqHh5np7zbai0lDQ/k2jsDD0gOhPFRxkGKfTGYiHrusFH/d/oKHlm6+3/nDNDUAl32uX5mr7BKv/IEr7lONoTtrb6Mke1rK/IUofe0igTx8vPPCTBkzWjn/UMtsKYUF+XQhCy63/5FdGWLT9qM3+QRHR7h7ouWINumRF3ZNY=
