apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
   name: sykepengesoknadfilter
   namespace: default
spec:
   image: navikt/sykepengesoknadfilter:2
   port: 8080
   team: teamhelse
   healthcheck:
      liveness:
         path: /isAlive
         initialDelay: 20
         timeout: 1
         periodSeconds: 5
         failureThreshold: 10
      readiness:
         path: /isReady
         initialDelay: 20
         timeout: 1
   replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 90
   prometheus:
      enabled: true
      path: /metrics
   secrets: true
