apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
   name: sykepengesoknadfilter
   namespace: helse
spec:
   image: navikt/sykepengesoknadfilter:1
   port: 8080
   team: teamhelse
   healthcheck:
      liveness:
         path: isAlive
         initialDelay: 20
         timeout: 1
         periodSeconds: 5
         failureThreshold: 10
      readiness:
         path: isReady
         initialDelay: 20
         timeout: 1
   replicas:
      min: 1
      max: 1
      cpuThresholdPercentage: 90
   prometheus:
      enabled: true
      path: /metrics
   secrets: true
